version: '3'

services:

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql-finance
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3307:3306
    # volumes:
    #   - //etc/localtime:/etc/localtime:ro # Windows WSL
    #   - //etc/timezone:/etc/timezone:ro # Windows WSL
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
    
  kafkadrop:
    image: obsidiandynamics/kafdrop
    container_name: kafkadrop-example
    ports:
      - 1000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-example:9092

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-example
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka
    container_name: kafka-example
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-example:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka-example:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 2048576
      KAFKA_CFG_MAX_REQUEST_SIZE: 2048576
    depends_on:
      - zookeeper

networks:
  example: