replicaCount: 2

image:
  repository: ismaelalvesdoc/express-finance
  tag: latest
  pullPolicy: Always
  livenessPath: /system/healthcheck

service:
  enabled: true
  type: NodePort

ingress:
  enabled: true
  host: ingress.local
  rewrite: /
  sslRedirect: false
  sslPassthrough: false
  forceSslRedirect: false
  proxySendTimeout: 3600
  proxyRendTimeout: 3600

env:
  NODE_ENV: production
  TZ: America/Fortaleza
  SERVER_PORT: 3000
  DB_HOST: kubernetes.docker.internal
  DB_PORT: 3306
  DB_USERNAME: root
  DB_DATABASE: finance
  DB_DEBUG: false
  REDIS_HOST: kubernetes.docker.internal
  REDIS_PORT: 6379
  REDIS_PREFIX: finance
  APM_SERVER_URL: http://kubernetes.docker.internal:8200
  APM_SERVICE_NAME: finance
  BRAPI_URL: https://brapi.ga/api
  MERCADO_BITCOIN_URL: https://www.mercadobitcoin.net
  YAHOO_FINANCE_URL: https://yfapi.net
  NEWS_URL: http://api.mediastack.com
  IEXCLOUND_URL: https://cloud.iexapis.com/stable
  IEXCLOUND_LIMIT_USAGE: 50000
  YIELD_URL: https://statusinvest.com.br
  CURRENCY_URL: https://economia.awesomeapi.com.br
  BCB_URL: https://www.bcb.gov.br
  EMAIL_TYPE: OAuth2
  EMAIL_USER: devmaelquel@gmail.com
  EMAIL_OAUTH2_REDIRECT_URI: https://developers.google.com/oauthplayground
  AMQP_PROTOCOL: amqp
  AMQP_HOSTNAME: kubernetes.docker.internal
  AMQP_PORT: 5672
  AMQP_USERNAME: finance
  AMQP_VHOST: /

secret:
  DB_PASSWORD: <admin>
  YAHOO_FINANCE_KEY: <key>
  AMQP_PASSWORD: <finance>
  EMAIL_OAUTH2_CLIENTID: <key>
  EMAIL_OAUTH2_CLIENTSECRET: <key>
  EMAIL_OAUTH2_REFRESHTOKEN: <key>
  IEXCLOUND_KEY: <pk_>
  IEXCLOUND_KEY_ADMIN: <sk_>
  NEWS_KEY: <key>
  APM_API_KEY: 
  APM_SECRET_TOKEN: 

resources:
  requests:
    memory: "700Mi"
    cpu: 400m
  limits:
    memory: "1Gi"
    cpu: 800m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70