replicaCount: 2

image:
  repository: ismaelalvesdoc/express-finance
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  type: NodePort

env:
  NODE_ENV: production
  TIME_ZONE: America/Fortaleza
  SERVER_ACTIVE: true
  SERVER_PORT: 3000
  SERVER_BODY_LIMIT: 500kb
  DB_HOST: kubernetes.docker.internal
  DB_PORT: 3306
  DB_USERNAME: root
  DB_DATABASE: finance
  DB_DEBUG: false
  REDIS_HOST: kubernetes.docker.internal
  REDIS_PORT: 6379
  REDIS_PREFIX: finance
  APM_SERVER_URL: http://kubernetes.docker.internal:8200
  APM_SERVICE_NAME: finance
  APM_API_KEY: 
  APM_SECRET_TOKEN: 

secret:
  DB_PASSWORD: admin

resources:
  requests:
    memory: "700Mi"
    cpu: 400m
  limits:
    memory: "1Gi"
    cpu: 800m

jobs:
  - name: update-investment
    schedule: "*/10 9-20 * * 1-5"
    namespace:
    labels: 
      jobgroup: "minute"  
    command: update-divideds

  - name: notify-currency
    schedule: "*/30 * * * * *"
    namespace:
    labels: 
      jobgroup: "second"  
    command: notify-currency

  - name: update-divideds
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "minute"  
    command: update-divideds

  - name: async-divideds-fiis
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: async-divideds-fiis

  - name: async-divideds-acao
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: async-divideds-acao

  - name: async-divideds-stoke
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: async-divideds-stoke

  - name: async-events-fiis
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: async-events-fiis

  - name: async-events-acao
    schedule: "0 10 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: async-events-acao

  - name: backup-data
    schedule: "0 20 * * *"
    namespace:
    labels: 
      jobgroup: "day"  
    command: backup-data

  - name: notify-price-day
    schedule: "10 18 * * 1-5"
    namespace:
    labels: 
      jobgroup: "day"  
    command: notify-price-day

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 70