---
# Source: finance/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: finance
  labels: 
     app: finance
     version: v1
     app.kubernetes.io/managed-by: Helm
  namespace: default
  annotations:
    meta.helm.sh/release-name: finance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finance
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 60
    type: Resource
  - resource:
      name: memory
      targetAverageUtilization: 70
    type: Resource
  minReplicas: 1
