---
# Source: finance/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: finance
  labels: 
    app: finance
    version: v1
    app.kubernetes.io/managed-by: Helm
  namespace: default
  annotations:
    meta.helm.sh/release-name: finance
data:
  DB_PASSWORD: "YWRtaW4="
  EMAIL_PASSWORD: "YWRtaW4="
  IEXCLOUND_KEY: "cGtfNWU2YmFjYzJjODVjNDIwZTg5N2JlNzQzNThkM2VlODE="
  IEXCLOUND_KEY_ADMIN: "c2tfM2Y2Yzc5OGU0MWFkNDg2YmIzNGQxZmM0YTM1ZmZjMWE="
  NEWS_KEY: "OTRmOTNiZjUwODI3NmMxOTBiY2M3MTNlYjk0NTJlNWQ="
  YAHOO_FINANCE_KEY: "Z2h0UXZMTHM4SmFEc3JtRUZsTmF3OWJsMm5ydUoybkM2ZGdHVDBLTQ=="
