{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: {{ template "service.fullname" . }}-ingress
  {{- if or .Values.namespace .Release.Namespace }}
  namespace: {{ or .Values.namespace .Release.Namespace }}
  {{- end}}
  annotations:
    {{ include "service.annotations" . }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewrite }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ template "service.fullname" . }}
            port: 
              number: {{ .Values.env.SERVER_PORT }}
{{- end }}